version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: miodontologo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
